name: .NET Core Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Pode ajustar para a versão do .NET que você está usando

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test with coverlet
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      
    - name: Generate coverage report
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage/
